name: pipeline-de-test-pour-python

on: [push]

jobs:
  un-max-de-test-sur-mon-python:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v7 #Permet de cloner le rep sur la machine ubuntu
      - name: installation python #Installation de python sur la machine
        uses: actions/setup-python@v7
        with:
          python-version: '3.14.7'
    # - run: pip install -r requirements.txt #pour l'instant pas de requirements, mais au cas où
      - name: test de structure
        run: pip install pylint #Installation de pylint qui va regarder si la structure du code est OK 
        run: pylint calculatrice.py #test de pyltinth sur l'app calculatrice
      - name: pytest
        run: pip3 install pytest
        
