name: pipeline-de-test-pour-python-avec-container

on: [push]

jobs:
  pylionth:
    runs-on: ubuntu-latest
    container: python:3.14.7-slim
    steps:
      - uses: actions/checkout@v7
      - name: pylionth - Test de structure du code
        run: pip install pylint && pylint calculatrice.py #Analyse de la structure
  flake:
    runs-on: ubuntu-latest
    container: python:3.14.7-slim
    steps:
      - uses: actions/checkout@v7
      - name: flake8 - Test de structure du code n°2
        run: pip install flake8 && flake8 calculatrice.py
  pytest:
    runs-on: ubuntu-latest
    container: python:3.14.7-slim
    steps:
      - uses: actions/checkout@v7
      - name: pytest - Vérification de calcul #test si 1+1=2 par exemple, vérifie des calculs.
        run: pip install pytest && python3 -m pytest test_calculatrice.py -v
  pytest-cov:
    runs-on: ubuntu-latest
    container: python:3.14.7-slim
    steps:
      - uses: actions/checkout@v7
      - name: pytest-cov - Vérifie la couverture du code testé par la pipeline 
        run: pip install pytest-cov && pytest --cov=calculatrice test_calculatrice.py
  bandit:
    runs-on: ubuntu-latest
    container: python:3.14.7-slim
    steps:
      - uses: actions/checkout@v7
      - name: Bandit - Scan de vulnérabilité #Détecte des pratiques à risque en cybersécurité dans python           
        run: pip install bandit && bandit calculatrice.py
  mypy:
    runs-on: ubuntu-latest
    container: python:3.14.7-slim
    steps:
      - uses: actions/checkout@v7
      - name: Mypy -Vérifie les types en entrée #Par exemple vérifie que dans la fonction addition on attend bien des chiffres mais pas des lettres
        run: pip install mypy && mypy calculatrice.py